name: Vercel Preview Deployment

on:
  pull_request:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

permissions:
  pull-requests: write
  issues: write

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Generate preview url"
        id: preview-url
        run: |
          BRANCH_SHA=$(echo ${{ steps.extract_branch.outputs.branch }} | sha256sum | cut -c5-38)
          echo "https://PREVIEW_URL=$BRANCH_SHA.vercel.app" >> $GITHUB_OUTPUT

      - name: Find first vercel preview comment
        uses: peter-evans/find-comment@v2
        if: success() && github.event.number
        id: fc-first-comment
        with:
          issue-number: ${{ github.event.number }}
          body-includes: <!-- __VERCEL_DEPLOYMENT__ -->

      - name: Get preview environment domain
        id: vercel-preview-domain
        run: |
          REGEX="(__VERCEL_PREVIEW_URL: )(.*)( -->)"
          COMMENT_BODY="${{ steps.fc-first-comment.outputs.comment-body }}"

          [[ $COMMENT_BODY =~ $REGEX ]]

          if [[ ${BASH_REMATCH[2]} ]]; then
              echo "VERCEL_PREVIEW_URL=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
          else
              echo "No previous Preview Environment"
          fi

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc-first-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ğŸš§ Building preview environment... ğŸ—ï¸

            <!-- __VERCEL_DEPLOYMENT__ -->
          edit-mode: replace
          reactions: eyes

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Vercel CLI
        run: pnpm add vercel@latest --global

      - name: Install Vercel CLI
        run: pnpm add vercel@latest --global

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: vercel-domain
        run: |
          DOMAIN=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})

          echo "VERCEL_PREVIEW_URL=${DOMAIN}" >> $GITHUB_OUTPUT

      - name: Alias current deployment
        run: |
          vercel alias \
            ${{ steps.vercel-domain.outputs.VERCEL_PREVIEW_URL }} \
            ${{ steps.preview-url.outputs.PREVIEW_URL }} \
            --token=${{ secrets.VERCEL_TOKEN }}

      - name: Remove old preview
        run: |
          OLD_URL="${{ steps.vercel-preview-domain.outputs.VERCEL_PREVIEW_URL }}"
          if [ $OLD_URL ]; then
              vercel remove $OLD_URL --yes --token=${{ secrets.VERCEL_TOKEN }}
          else
              echo "No previous Preview Environment"
          fi

      - name: Find preview comment to update
        uses: peter-evans/find-comment@v2
        if: success() && github.event.number
        id: fc-comment-update
        with:
          issue-number: ${{ github.event.number }}
          body-includes: <!-- __VERCEL_DEPLOYMENT__ -->

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc-comment-update.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## [ğŸ§ Your preview environment is ready! ğŸ‰](${{ steps.preview-url.outputs.PREVIEW_URL }})

            <!-- __VERCEL_DEPLOYMENT__ -->
            <!-- __VERCEL_PREVIEW_URL: ${{ steps.vercel-domain.outputs.VERCEL_PREVIEW_URL }} -->
